version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 241328210249.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo building the Jar file
      - mvn clean install -DskipTests          
      - docker build -t sample-app .
      - docker tag sample-app:latest 241328210249.dkr.ecr.ap-south-1.amazonaws.com/sample-app:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $241328210249.dkr.ecr.ap-south-1.amazonaws.com/sample-app:latest
      - echo writing image definitions file....
      - printf '[{"name":"sampel-app", "imageUri":"%s"}]' 241328210249.dkr.ecr.ap-south-1.amazonaws.com/sample-app:latest > imagedefinitions.jason
artifacts:
  files:
      - imagedefinitions.jason
      - targer/sample-app-1.0.0-SNAPSHOT.jar
